name: gestion_chantier
description: Application de gestion de chantier

publish_to: 'none' # Pas de publication

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.5.0
  # ajoute aussi d’autres si besoin


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_mrg.jpg
    - assets/images/chantier.png
    - assets/images/salarie.png
    - assets/images/chantier_en_cours.png
    - assets/images/chantier_termine.png
