// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA016tbFbGDMR359xjSBQj8jhYv0qfH654',
    appId: '1:562505786244:web:76defbccd5b10ea09933d1',
    messagingSenderId: '562505786244',
    projectId: 'chantiers-mrg',
    authDomain: 'chantiers-mrg.firebaseapp.com',
    storageBucket: 'chantiers-mrg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkLzU8VYUps59vPJDyzMjXbJLsM9A_1E',
    appId: '1:562505786244:android:01eb54852d98a7c49933d1',
    messagingSenderId: '562505786244',
    projectId: 'chantiers-mrg',
    storageBucket: 'chantiers-mrg.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA016tbFbGDMR359xjSBQj8jhYv0qfH654',
    appId: '1:562505786244:web:ef5ed768f9e850669933d1',
    messagingSenderId: '562505786244',
    projectId: 'chantiers-mrg',
    authDomain: 'chantiers-mrg.firebaseapp.com',
    storageBucket: 'chantiers-mrg.firebasestorage.app',
  );

}